spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
