apiVersion: v1
kind: Namespace
metadata:
  name: reservas
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reservas-backend-config
  namespace: reservas
data:
  JWT_EXPIRATION_SECONDS: "1800"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:5173,http://localhost:8080"
